### ISSUE TITLE
Sveltekit example doesn't work

### ISSUE THREAD

**Issue by Etheonor** [directus/examples#69]
I tried to fix it during two hours but without success... I also tried the next.js example to compare and everything's fine. 

I have this error:
`Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///F:/Git/svelteDirectus/sveltekit/.svelte-kit/runtime/server/index.js:1824:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async load (index.svelte:6:21)
    at async load_node (file:///F:/Git/svelteDirectus/sveltekit/.svelte-kit/runtime/server/index.js:1853:12)
    at async respond$1 (file:///F:/Git/svelteDirectus/sveltekit/.svelte-kit/runtime/server/index.js:2222:15)
    at async render_page (file:///F:/Git/svelteDirectus/sveltekit/.svelte-kit/runtime/server/index.js:2423:19)
    at async resolve (file:///F:/Git/svelteDirectus/sveltekit/.svelte-kit/runtime/server/index.js:2697:11)
    at async respond (file:///F:/Git/svelteDirectus/sveltekit/.svelte-kit/runtime/server/index.js:2594:20)
    at async file:///F:/Git/svelteDirectus/sveltekit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.295_svelte@3.46.4/node_modules/@sveltejs/kit/dist/chunks/index`

The response.status on index.svelte (line 5) is 404, so I think there is an issue to access the endpoint.

**Comment by azrikahar** [comment]
Hi, I've tried it on my end and it seems to work. However, I was able to replicate the issue if I _do not_ create the `.env` as per the 3rd step mentioned by the readme over here: https://github.com/directus/examples/tree/main/sveltekit

Is the file present? If not, can you try following the 3rd step and let us know how it goes? We'll reopen this issue if it still persists after that 👍

---

That being said, I believe this still warrants a better exception handling so I've updated it and ensured the example will remind users about it if they missed that particular step:

![image](https://user-images.githubusercontent.com/42867097/158066589-b2bba24f-eedd-4fdd-a8e1-00749ba4283e.png)

**Comment by Etheonor** [comment]
Well the thing is, I have the .env file in my project. 

The SvelteKit endpoint is working because if I console.log(formattedArticles) at the end, I have the correct result. But for some reason, it's the call to this endpoint in index.svelte that doesn't seems to work. 

![image](https://user-images.githubusercontent.com/35852770/158070371-ff104138-fc1a-4f43-b9f9-c5c6cbc93f31.png)

This first screen show that if I console log the result, I received something from Directus. But on the second screen below, for some reason, fetch isn't working. 

![image](https://user-images.githubusercontent.com/35852770/158070453-0b6831da-6100-4a81-9eb7-529bbcfd559b.png)

**Comment by Etheonor** [comment]
Ok I found something, and it has to do with the last version of Sveltekit. 

I tried to install and old version (1.0.0-next.206 instead of next), and it works. But right now, I have now idea why and what changed

**Comment by azrikahar** [comment]
Thank you for pinpointing the exact version that is no longer compatible! Seems like [`1.0.0-next.260`](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next260) implemented something called [shadow endpoints](https://github.com/sveltejs/kit/pull/3679) so the previous implementations such as `index.json.js` file doesn't seem to work anymore.

Good news is I believe I've updated the example accordingly and it should work if you pull the latest changes. Let me know if there's any issues once you get the chance to try it out 👍

Going forward I believe we'll pin all the frameworks' versions just to be sure, since it can be difficult to keep up with all of them (at least for me personally at this point in time). But help such as yours, especially with detailed troubleshooting & investigation, makes it so much easier to find a fix. Thanks again!

**Comment by Etheonor** [comment]
It works perfectly with your last commit! 

And no problem for the bug report, I know how debugging can be a pain ^^ And yes especially with frameworks in beta like Sveltekit, stick to a specific version can avoid a lot of trouble!
